

export const LANGUAGE = {
  'en' : {
      lang : 'en',
      featured_products_title : 'Featured Products',
      featured_products_desc : 'Most wanted products',
      imagesdisplay_title : 'All purpose cleaning products',
      imagesdisplay_restaurant : 'Restaurant Cleaning',
      imagesdisplay_kitchen : 'Kitchen Cleaning',
      imagesdisplay_commercial : 'Commercial Cleaning',
      productcard_buttomwhatsapp : 'WhatsApp',
      productcard_buttomsms : 'SMS',
      productcard_message : "Hi, I'm interested in the product: ",
      hero_title : 'Sebastian Mejia',
      hero_subtitle : "Explore cleaning excellence for restaurants with the market's lowest prices. Transform your kitchen with our high-quality products, achieving the impossible combination of effectiveness and affordability.",
      hero_buttom : 'Shop',
      listproducts_buttom : 'See all products',
      listproducts_title : 'Shop',
      contactform_title : 'Contact Us',
      contactform_message1 : 'My name is ',
      contactform_message2 : 'Thank you',
      contactform_nameinput : 'Name',
      contactform_messageinput : 'Message',
      contactform_anchorwhatsapp : 'Contact WhatsApp',
      contactform_anchortext : 'Contact Text Message',
      footer_contactstitle : 'Contacts',
      footer_socialstitle : 'Socials',
  },
  'es' : {
    lang : 'es',
    featured_products_title : 'Productos Destacados',
    featured_products_desc : 'Productos más buscados',
    imagesdisplay_title : 'Productos de limpieza multiusos',
    imagesdisplay_restaurant : 'Limpieza de restaurantes',
    imagesdisplay_kitchen : 'Limpieza de cocinas',
    imagesdisplay_commercial : 'Limpieza comercial',
    productcard_buttomwhatsapp : 'WhatsApp',
    productcard_buttomsms : 'SMS',
    productcard_message : "Hola estoy interesado en el producto: ",
    hero_title : 'Sebastian Mejia',
    hero_subtitle : 'Descubre la excelencia en limpieza para restaurantes con los precios más bajos del mercado. Transforma tu cocina con nuestros productos de alta calidad, logrando la imposible combinación de eficacia y asequibilidad.',
    hero_buttom : 'Comprar',
    listproducts_buttom : 'Ver todos los productos',
    listproducts_title : 'Comprar',
    contactform_title : 'Contáctanos',
    contactform_message1 : 'Mi nombre es ',
    contactform_message2 : 'Gracias',
    contactform_nameinput : 'Nombre',
    contactform_messageinput : 'Mensaje',
    contactform_anchorwhatsapp : 'Contactar por WhatsApp',
    contactform_anchortext : 'Contactar por mensaje de texto',
    footer_contactstitle : 'Contactos',
    footer_socialstitle : 'Redes Sociales',
}

}